languageCode: "en"
title: "Auto Clicker AutoFill"
baseURL: "https://blog.getautoclicker.com"
enableInlineShortcodes: true

taxonomies:
  category: categories
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 6

buildDrafts: true
buildFuture: true
rssLimit: 1

enableRobotsTXT: true
metaDataFormat: "yaml"
disableKinds: ["404", "taxonomyTerm"]

publishDir: "docs"

permalinks:
  /: "/:slug/"

module:
  mounts:
    - source: node_modules/bootstrap/dist
      target: static/bootstrap/dist
    - source: static
      target: static

params:
  name: "Auto Clicker - AutoFill"
  description: "Auto Click / Auto Fill is like a utility extension which helps user to click / fill on any website with by providing few information about the site and the button which they want to click."
  docs_version: "3.x"
  social_image_path: "https://getautoclicker.com/docs/3.x/assets/brand/bootstrap-social.png"
  social_logo_path: "https://getautoclicker.com/docs/3.x/assets/brand/bootstrap-social-logo.png"
  authors: "Dhruv Patel, Dharmesh Patel, and AutoClicker contributors"
  github_org: "https://github.com/dhruv-techapps"
  repo: "https://github.com/dhruv-techapps/auto-click-auto-fill"
  twitter: "dhruvtechapps"
  discord: "https://discord.gg/vmnNfWKqnR"
  youtube: "https://www.youtube.com/channel/UCj1acOGkIYR59furcg28nzA"
  blog: "https://blog.getautoclicker.com/"
  configs: "https://configs.getautoclicker.com/"
  Home: "https://getautoclicker.com/"
  docs: "https://getautoclicker.com/docs/3.x/getting-started/introduction/"
  download: "https://getautoclicker.com/docs/3.x/getting-started/download/"
  stable: "https://stable.getautoclicker.com"
  beta: "https://beta.getautoclicker.com"
  dev: "https://dev.getautoclicker.com"
  
  cdn:
    css: "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
    css_hash: "sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
    js: "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"
    js_hash: "sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG"
    js_bundle: "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
    js_bundle_hash: "sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
    popper: "https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"
    popper_hash: "sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi"
