languageCode: 'en'
title: 'Auto Clicker AutoFill Blog'
baseURL: 'https://blog.getautoclicker.com'
enableInlineShortcodes: true

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 6

buildDrafts: true
buildFuture: true

enableRobotsTXT: true
metaDataFormat: 'yaml'

disableKinds: ['404', 'taxonomy', 'term']

publishDir: '_site'

paginate: 5
rssLimit: 10

permalinks:
  posts: '/:slug/'

related:
  includeNewer: false
  indices:
    - name: keywords
      weight: 100
    - name: tags
      weight: 80
    - name: date
      weight: 10
  threshold: 80
  toLower: false

outputs:
  page: ['HTML']
  home: ['HTML', 'RSS']
  section: ['HTML', 'RSS']

outputFormats:
  RSS:
    mediatype: 'application/rss'
    baseName: 'feed'

module:
  mounts:
    - source: node_modules/bootstrap/dist
      target: static/bootstrap/dist
    - source: src/assets
      target: assets
    - source: src/content
      target: content
    - source: src/data
      target: data
    - source: src/layouts
      target: layouts
    - source: src/static
      target: static
    - source: src/static/assets/img/favicons/apple-touch-icon.png
      target: static/apple-touch-icon.png
    - source: src/static/assets/img/favicons/favicon.ico
      target: static/favicon.ico
    - source: node_modules/bootstrap/scss
      target: assets/scss/bootstrap
    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
      target: assets/js/bootstrap.bundle.min.js

params:
  docs_version: '3.x'
  description:
    'Auto Click / Auto Fill is like a utility extension which helps user to click / fill on any website with by providing few information about the site and the button which they want to click.'
  authors: 'Dhruv Techapps, Dharmesh Patel'
  author: 'Dhruv Techapps'
  main: 'https://getautoclicker.com'
  github_org: 'https://github.com/dhruv-techapps'
  repo: 'https://github.com/dhruv-techapps/blog'
  twitter: 'getautoclicker'
  blog: 'https://blog.getautoclicker.com/'
  discord: 'https://discord.gg/vmnNfWKqnR'
  google_group: 'https://groups.google.com/g/auto-clicker-autofill'
  opencollective: 'https://opencollective.com/auto-clicker-autofill'
  youtube: 'https://www.youtube.com/channel/UCj1acOGkIYR59furcg28nzA'
  stable: 'https://stable.getautoclicker.com'
  beta: 'https://beta.getautoclicker.com'
  dev: 'https://dev.getautoclicker.com'

  # This is currently used by Hugo's internal twitter_cards.html and opengraph.html templates;
  # the first image in the following array is always used, unless specified in the front matter
  images:
    - '/assets/img/bootstrap-social.png'
  cdn:
    js_bundle: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js'
    js_bundle_hash: 'sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN'
social:
  twitter: 'dhruv-techapps'
